config/routes.rb
Rails.application.routes.draw do
  resources :people

  resources :events

  resources :schools

    root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
  validates :description, length: { maximum: 140 }

  belongs_to :person
  validates :person, presence: true
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true

  has_many :events
  has_many :schools
end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true
  validates :year_start, presence: true, numericality: { only_integer: true }
  validates :year_end, presence: true,
                       numericality: { only_integer: true,
                                       greater_than_or_equal_to: :year_start }

  belongs_to :person
  validates :person, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :year, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @schools = @person.schools
    @events = @person.events
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :year_start, :year_end, :person_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @events = Event.all
    @schools = School.all
    @feed = @schools
    @events.each do |e|
      @feed.push e
    end
#    @feed = @feed.order(:created_at)  ## Always breaks :(

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

  def display(e)
    if e.has_attribute?(:name)
     "#{e.person.name} added a new school:  #{e.name} from #{e.year_start} to #{e.year_end}."
    elsif e.has_attribute?(:title)
      "#{e.person.name} added a new event: #{e.title} in #{e.year}."
    end
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="field small-4 columns">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
</div>
<div class="row">
  <div class="field small-4 columns">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="field small-4 columns">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
</div>
</div>
<div class="row">
  <div class="actions small-4 columns">
    <%= f.submit %>
  </div>
</div>

<div class="row">
  <div class="field small-4 columns">
    <%= f.label :person_id, "Person"%><br>
    <%= f.collection_select :person_id, Person.all, :id, :name %>
  </div>
</div>


<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.year %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Year:</strong>
  <%= @event.year %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">

  <%= yield %>
  <%= javascript_include_tag "application" %><br>

  <div class="row">
    <div class="actions small-4 columns">
      <%= link_to "Home", root_path %>
    </div>
  </div>

</div>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<h2>Events</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
  <% @events.order(:year).each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.year %></td>
      <td><%= link_to 'Show', event %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

<h2>Schools</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year start</th>
      <th>Year end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
  <% @schools.each do |school| %>
    <tr>
      <td><%= school.name %></td>
      <td><%= school.year_start %></td>
      <td><%= school.year_end %></td>
      <td><%= link_to 'Show', school %></td>
      <td><%= link_to 'Edit', edit_school_path(school) %></td>
      <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
<% if @school.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

  <ul>
    <% @school.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="field small-4 columns">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
</div>
<div class="row">
  <div class="field small-4 columns">
    <%= f.label :year_start %><br>
    <%= f.number_field :year_start %>
  </div>
</div>
<div class="row">
  <div class="field small-4 columns">
    <%= f.label :year_end %><br>
    <%= f.number_field :year_end %>
  </div>
</div>

<div class="row">
  <div class="field small-4 columns">
    <%= f.label :person_id, "Person"%><br>
    <%= f.collection_select :person_id, Person.all, :id, :name %>
  </div>
</div>




<div class="row">
  <div class="actions small-4 columns">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year start</th>
      <th>Year end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.year_start %></td>
        <td><%= school.year_end %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Year start:</strong>
  <%= @school.year_start %>
</p>

<p>
  <strong>Year end:</strong>
  <%= @school.year_end %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/welcome/index.html.erb
<h2>Welcome!</h2>

<p><%=link_to "Identify yourself", new_person_path %>, then create a new <%= link_to "life event", events_path %> or <%= link_to "add a school", schools_path %>.</p>

<% @feed.each do |s| %>
  <%= display(s) %><br>
<% end %>